Repository AndrewLeinster/CW2-API-Mashup-Group-5, pull requests merged in 2022-12, with the labels that each got.

#14 Adding folders to make repo easier to navigate.
  .DS_Store
  CSS/cityBikes.jpg
  CSS/custom.css
  Javascript/test_page.js
  Pages/about.html
  Pages/duckPage.html
  Pages/moreInfo.html
  Pages/test_page.html
  index.html
Labels: Updates

#10 added more styling and applied css to all pages
  about.html
  custom.css
  duckPage.html
  index.html
  moreInfo.html
Labels: New Feature

#12 Updating homepage, visual updates only
  custom.css
  index.html
Labels: Updates

#20 Creating folders + updating links
  CSS/custom.css
  Images/cityBikes.jpg
  Individual pages/about.html
  Individual pages/duckPage.html
  Individual pages/moreInfo.html
  Individual pages/test_page.html
  Javascript/test_page.js
  index.html
Labels: enhancement

#24 Fixing linking CSS
  Styling/cityBikes.jpg
  Styling/custom.css
  index.html
Labels: enhancement, fix

#33 changes to styling
  .DS_Store
  Individual pages/duckPage.html
  Styling/custom.css
  index.html
Labels: Updates

#42 More info js
  Individual pages/moreInfo.html
  Javascript/more_info.js
  Javascript/weather.js
Labels: New Feature

#44 Changing pathing for pages
  Pages/about.html
  Pages/duckPage.html
  Pages/moreInfo.html
  Pages/test_page.html
  index.html
Labels: fix

#45 Applying style changes to moreinfo page
  .DS_Store
  Javascript/more_info.js
  Javascript/weather.js
  Pages/moreInfo.html
  Styling/custom.css
  index.html
Labels: Updates

#47 attempt 2?
  Javascript/weather.js
Labels: bug, fix

#48 Still trying to fix linking to moreinfo in repo
  Javascript/weather.js
  Pages/.DS_Store
  Pages/moreInfo.html
  Styling/custom.css
Labels: help wanted, fix

#52 Duckpage fixes
  Javascript/test_page.js
  Pages/duckPage.html
  Pages/moreInfo.html
  Styling/custom.css
Labels: Updates

#51 styling fixed
  .DS_Store
  Styling/custom.css
Labels: Updates

#53 made about page pretty
  Pages/about.html
  Styling/custom.css
Labels: enhancement

#55 Adding lightmode
  Pages/about.html
  Pages/duckPage.html
  Pages/moreInfo.html
  Pages/test_page.html
  Styling/lightmode.css
  index.html
Labels: Updates

#54 Adding text to homepage
  Styling/custom.css
  index.html
Labels: New Feature

#64 Cssupdates
  Javascript/dark_mode.js
  Javascript/theme_index.js
  Javascript/theme_pages.js
  Javascript/weather.js
  Pages/about.html
  Pages/duckPage.html
  Pages/moreInfo.html
  Styling/darkmode.css
  Styling/lightmode.css
  bootstrap/bootstrap.min.css
  index.html
Labels: Updates, fix

#63 Bikes js
  Javascript/bikes.js
  index.html
Labels: New Feature

#62 started adding favourites feature
  .DS_Store
  Javascript/weather.js
  Styling/.DS_Store
  Styling/darkmode.css
  Styling/lightmode.css
  index.html
Labels: bug, New Feature

#77 Bikes javascript added to more info page
  Javascript/bikes.js
  Javascript/more_info.js
  Javascript/weather.js
  Pages/moreInfo.html
  Styling/darkmode.css
  Styling/lightmode.css
  index.html
Labels: New Feature

#80 Update more info page
  Javascript/bikes.js
  Javascript/more_info.js
  Pages/moreInfo.html
Labels: enhancement, fix

#82 styling changes
  Javascript/weather.js
  Styling/darkmode.css
  Styling/lightmode.css
Labels: Updates

#83 made pwa
  Pages/about.html
  Pages/duckPage.html
  Pages/faq.html
  Pages/moreInfo.html
  Pages/termsOfService.html
  Pages/test_page.html
  Styling/lightmode.css
  index.html
  manifest.json
  service-worker.js
Labels: Updates

#96 Adding favourites now works
  Javascript/bikes.js
  Javascript/weather.js
  index.html
Labels: Updates, New Feature

#109 clear button fixed
  Javascript/weather.js
Labels: fix

#112 new icon
  .DS_Store
  Styling/.DS_Store
  Styling/PWAicon-144.png
Labels: Updates

#115 footer and pwa body colour
  Pages/about.html
  Pages/duckPage.html
  Pages/faq.html
  Pages/moreInfo.html
  Pages/termsOfService.html
  Styling/darkmode.css
  Styling/lightmode.css
  index.html
Labels: Updates, fix

#117 Trying to add container to favourites
  Javascript/weather.js
  index.html
Labels: Updates

#122 updating favourite styling
  Javascript/weather.js
  Styling/darkmode.css
  Styling/lightmode.css
Labels: Updates
